version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: maven
    directory: "plugin/"
    schedule:
      interval: monthly