version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
        - "*"
  - package-ecosystem: gradle
    directory: "plugin/"
    schedule:
      interval: monthly
    groups:
      gradle-dependencies:
        patterns:
        - "*"
