plugins {
    id 'java-gradle-plugin'
    id 'jvm-test-suite'
    id 'com.gradle.plugin-publish' version '2.1.1'
    id 'pmd'
}

group = "org.gauge.gradle"

repositories {
    mavenLocal()
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

pmd {
    consoleOutput = true
}

testing {
    suites {
        configureEach {
            useJUnitJupiter()
            dependencies {
                implementation gradleApi()
                implementation "org.junit.jupiter:junit-jupiter:6.+"
                runtimeOnly "org.junit.platform:junit-platform-launcher"
            }
        }
        integrationTest(JvmTestSuite) {
            dependencies {
                implementation project()
                implementation gradleTestKit()
                implementation "commons-io:commons-io:2.21.+"
                implementation "org.hamcrest:hamcrest:3.0"
            }

            targets {
                all {
                    testTask.configure {
                        shouldRunAfter(tasks.named("test"))
                    }
                }
            }
        }
    }
}

tasks.withType(Test).configureEach {
    testLogging {
        showStandardStreams = true
        showStackTraces = true
        exceptionFormat = 'full'
        events = ["passed", "failed", "skipped"]
    }
}

tasks.named('check') {
    dependsOn(testing.suites.integrationTest)
}

gradlePlugin {
    testSourceSets(sourceSets.integrationTest)
    plugins {
        gauge {
            id = "org.gauge"
            implementationClass = "org.gauge.gradle.GaugePlugin"
            displayName = "Gauge"
            description = "Gradle plugin for Gauge, the open source test automation tool developed by ThoughtWorks."
            tags = ['gauge', 'thoughtworks', 'testing']
        }
    }
    vcsUrl = "https://github.com/getgauge/gauge-gradle-plugin.git"
    website = "https://github.com/getgauge/gauge-gradle-plugin"
}