# Allow Gauge to download template from insecure URLs.
allow_insecure_download=false
# Allow Gauge and its plugin updates to be notified.
check_updates=true
# Url to get plugin versions
gauge_repository_url=https://downloads.gauge.org/plugin
# Timeout in milliseconds for requests from runner when invoked for ide.
ide_request_timeout=30000
# The maximum number of backup log files to retain.
log_max_backups_count=3
# Timeout in milliseconds for making a connection to plugins.
plugin_connection_timeout=10000
# Timeout in milliseconds for a plugin to stop after a kill message has been sent.
plugin_kill_timeout=4000
# Timeout in milliseconds for making a connection to the language runner.
runner_connection_timeout=300000
# Timeout in milliseconds for requests from the language runner.
runner_request_timeout=300000
# Whether to validate dependency and plugin versions
gauge_dependency_validation=false